//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace ClubApi.Models
{
    using System;

    public partial class PERSONA
    {
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string mail { get; set; }
        public Nullable<int> salario { get; set; }
        public Nullable<System.Guid> idClub { get; set; }
        public bool tipo { get; set; }

        [JsonIgnore]
        public virtual CLUB CLUB { get; set; }
    }
}
